# sampling and population

In [1]:
#Exp no.:6

In [2]:
#to perform sampling and population

In [3]:
#Name:Vedant Dalvi
#Roll No:12
#Sec:C
#Subject:DSS
#Date:20/08/2026

In [3]:
import pandas as pd

In [4]:
import os

In [5]:
os.getcwd()

'C:\\Users\\HP'

In [6]:
os.chdir("C:\\Users\\HP")

In [11]:
data=pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\heart.csv")

In [12]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [10]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [17]:
#filter records where age is greater than 60
age_above_60 = data[data["age"] > 60]

#Display(age_above_60)
print(age_above_60)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
13    64    1   3       110   211    0        0      144      1      1.8
17    66    0   3       150   226    0        1      114      0      2.6
19    69    0   3       140   239    0        1      151      0      1.8
23    61    1   2       150   243    1        1      137      1      1.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
290   61    1   0       148   203    0        1      161      0      0.0
293   67    1   2       152   212    0        0      150      0      0.8
295   63    1   0       140   187    0        0      144      1      4.0
296   63    0   0       124   197    0        1      136      1      0.0
300   68    1   0       144   193    1        1      141      0      3.4

     slope  ca  thal  target
0        0   0     1       1
13       1   0     2       1
17       0   0     2       1
19       2   2     2       1
23       1   0     2       1
..     ...  ..   ...     ...
290      2   1     3       0
293      1   0     3       0
295      2   2     3       0
296      1   0     2       0
300      1   2     3       0

[79 rows x 14 columns]

In [18]:
print("the number of patients above 60 is :",len(age_above_60))

the number of patients above 60 is : 79

In [19]:
data.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [20]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [21]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64